-- TODO rename field name

COPY customers (CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
FROM 'C:/POSTCUR/customers.csv'
WITH (FORMAT csv, HEADER false, DELIMITER ';', QUOTE '"');

COPY products (CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA)
FROM 'C:/POSTCUR/products.csv'
WITH (FORMAT csv, HEADER false, DELIMITER ';', QUOTE '"');

COPY salesmans (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO)
FROM 'C:/POSTCUR/salesmans.csv'
WITH (FORMAT csv, HEADER false, DELIMITER ';', QUOTE '"');

COPY frutally.invoices (CPF, MATRICULA, DATA_VENDA, NUMERO, IMPOSTO)
FROM 'C:/POSTCUR/invoices.csv'
WITH (FORMAT csv, HEADER false, DELIMITER ';', QUOTE '"');

COPY frutally.invoice_items (NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO)
FROM 'C:/POSTCUR/invoice_items.csv'
WITH (FORMAT csv, HEADER false, DELIMITER ';', QUOTE '"');
